project_id = "mjbxpjaxczoycrcjajio"

[functions.sms-receive]
verify_jwt = false

[functions.create-order]
verify_jwt = false

[functions.verify-payment]
verify_jwt = false

[functions.order-status]
verify_jwt = false

[functions.headadmin-delete-user]
verify_jwt = false

[functions.headadmin-delete-user-messages]
verify_jwt = false

[functions.headadmin-update-user-plan]
verify_jwt = false

[functions.ai-reply]
verify_jwt = false

[functions.tag-product-image]
verify_jwt = false

[functions.woo-webhook]
verify_jwt = false

[functions.crm-woo-order-webhook]
verify_jwt = false

[functions.crm-whatsapp-webhook]
verify_jwt = false

[functions.crm-book-courier]
verify_jwt = false

[functions.crm-cod-send]
verify_jwt = false

[functions.send-manual-media]
verify_jwt = true

[functions.match-product-image]
verify_jwt = false

[functions.send-product-image-to-customer]
verify_jwt = false

[functions.wa-send-text]
verify_jwt = false

[functions.wa-send-image]
verify_jwt = false

[functions.wa-send-voice]
verify_jwt = false

[functions.wa-send-video]
verify_jwt = false

[functions.wa-send-document]
verify_jwt = false

[functions.wa-download-media]
verify_jwt = false
